basePath: /
definitions:
  dto.ApiError:
    properties:
      detail:
        example: Some error details
        type: string
      status:
        example: 503
        type: integer
      title:
        example: err_code
        type: string
    type: object
  dto.BookCreateIn:
    properties:
      items:
        example: 46
        type: integer
      name:
        example: The Book of Eli
        type: string
    type: object
  dto.BookUpdateIn:
    properties:
      id:
        example: 24
        type: integer
      items:
        example: 46
        type: integer
      name:
        example: The Book of Eli
        type: string
    type: object
  models.Book:
    properties:
      createdAt:
        example: "2021-03-12T02:11:03.292442-05:00"
        type: string
      id:
        example: 24
        type: integer
      items:
        example: 46
        type: integer
      name:
        example: The Book of Eli
        type: string
      updatedAt:
        example: "0001-01-01T00:00:00Z"
        type: string
    type: object
host: localhost:8080
info:
  contact:
    email: sample@mail.io
    name: Name Test
    url: http://contact.sample/text
  description: Api description shell project
  title: Shell Project
  version: "0.0"
paths:
  /books:
    get:
      description: Get the books in the repository
      produces:
      - application/json
      responses:
        "200":
          description: List of Books
          schema:
            items:
              $ref: '#/definitions/models.Book'
            type: array
        "500":
          description: err.repo_ops
          schema:
            $ref: '#/definitions/dto.ApiError'
      summary: Get Books
      tags:
      - Books
    post:
      consumes:
      - application/json
      description: Create a new book from the passed data
      parameters:
      - description: Book Data
        in: body
        name: book
        required: true
        schema:
          $ref: '#/definitions/dto.BookCreateIn'
      produces:
      - application/json
      responses:
        "201":
          description: OK
          schema:
            $ref: '#/definitions/models.Book'
        "422":
          description: "err.duplicate_key || Invalid data\"\t// TODO learn to make
            validation of params and body, make the response 400 (bad request)"
          schema:
            $ref: '#/definitions/dto.ApiError'
        "500":
          description: err.repo_ops || Internal error
          schema:
            $ref: '#/definitions/dto.ApiError'
      summary: Create a new book
      tags:
      - Books
  /books/{id}:
    delete:
      consumes:
      - application/json
      description: Deletes a Book by its Id
      parameters:
      - description: Book ID
        format: uint32
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "204":
          description: No Content
        "404":
          description: err.not_found
          schema:
            $ref: '#/definitions/dto.ApiError'
        "500":
          description: err.repo_ops
          schema:
            $ref: '#/definitions/dto.ApiError'
      summary: Delete a Book
      tags:
      - Books
    get:
      consumes:
      - application/json
      description: Get a book through its Id
      parameters:
      - description: Requested Book Id
        format: uint32
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Book'
        "404":
          description: err.not_found
          schema:
            $ref: '#/definitions/dto.ApiError'
        "500":
          description: Internal error
          schema:
            $ref: '#/definitions/dto.ApiError'
      summary: Get book by Id
      tags:
      - Books
    put:
      consumes:
      - application/json
      description: Update the book having the specified Id with the data passed in
        the request body
      parameters:
      - description: Book ID
        format: uint32
        in: path
        name: id
        required: true
        type: integer
      - description: Book Data
        in: body
        name: book
        required: true
        schema:
          $ref: '#/definitions/dto.BookUpdateIn'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Book'
        "404":
          description: err.not_found
          schema:
            $ref: '#/definitions/dto.ApiError'
        "422":
          description: "err.duplicate_key || Invalid data\"\t// TODO learn to make
            validation of params and body, make the response 400 (bad request)"
          schema:
            $ref: '#/definitions/dto.ApiError'
        "500":
          description: err.repo_ops || Internal error
          schema:
            $ref: '#/definitions/dto.ApiError'
      summary: Update the indicated book
      tags:
      - Books
swagger: "2.0"
