basePath: /
definitions:
  models.Book:
    properties:
      title:
        type: string
    type: object
host: localhost:8080
info:
  contact:
    email: sample@mail.io
    name: Name Test
    url: http://contact.sample/text
  description: Api description shell project
  title: Shell Project
  version: "0.0"
paths:
  /books:
    get:
      description: Get all the books
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/data.Book'
            type: array
      summary: Books
      tags:
      - books
    post:
      description: Create a book
      produces:
      - application/json
      responses:
        "200":
          description: ok
          schema:
            type: string
      summary: Books
      tags:
      - books
  /catalogs:
    get:
      description: Get all the books
      produces:
      - application/json
      responses:
        "200":
          description: ok
          schema:
            $ref: '#/definitions/data.Book'
      summary: Catalog
      tags:
      - catalogs
    post:
      description: Get all the books
      produces:
      - application/json
      responses:
        "200":
          description: ok
          schema:
            type: string
      summary: Catalog
      tags:
      - catalogs
swagger: "2.0"
